YouPorn Términos de Servicio

1. ACEPTACIÓN
Mediante el uso y / o visitar el sitio web de YouPorn (colectivamente, incluyendo pero no limitado a todo el contenido, Cargas y envíos de usuario disponibles a través YouPorn.com "YouPorn", el sitio web) usted acepta los términos y condiciones contenidos Herin y los términos y condiciones de Herin política de privacidad incorporada de YouPorn, y todas las futuras enmiendas y modificaciones (referidos colectivamente como el "Acuerdo"). Al participar, usted acepta que quedará vinculado por estos términos y condiciones. Si no acepta estar sujeto a los términos y condiciones contenidos en el presente documento, entonces no use YouPorn.com.
Los términos y condiciones de este acuerdo están sujetos a cambios por YouPorn en cualquier momento ya su sola discreción, y usted acepta estar obligado por todas las modificaciones, cambios y / o revisiones. Si usted no acepta que quedará vinculado por cualquier y todas las modificaciones, cambios y / o revisiones de este acuerdo, que muchos de ellos no utiliza YouPorn.com.
Los términos y condiciones contenidos en este documento se aplican a todos los usuarios de YouPorn si un "visitante" o un "miembro" y que sólo están autorizados a usar YouPorn.com si está de acuerdo en cumplir con todas las leyes aplicables y estar legalmente obligado por los términos y condiciones de este Acuerdo.
Volver arriba
2. DESCRIPCIÓN
La página web YouPorn permite subir, compartir y general de ver varios tipos de contenido que permite a los usuarios registrados y no registrados para compartir y ver representaciones visuales de contenido para adultos, incluyendo imágenes sexualmente explícitas. Además, YouPorn contiene contenido de video, información y otros materiales publicados / subido por los usuarios. YouPorn permite a sus usuarios ver el contenido y el Sitio Web con sujeción a los términos y condiciones de este Acuerdo.
La página web YouPorn también puede contener ciertos enlaces a sitios web de terceros que son de ninguna manera posee o controla YouPorn. YouPorn no asume ninguna responsabilidad por el contenido, políticas de privacidad, las prácticas de cualquier y todos los sitios web de terceros. YouPorn no puede censurar o editar el contenido de sitios de terceros. Usted reconoce que youporn no será responsable por cualquier y toda responsabilidad derivada de su uso de cualquier sitio web de terceros.
YouPorn.com es para su uso personal y no podrá ser utilizada para cualquier emprendimiento comercial excepto aquellos específicamente endosado o aprobado por YouPorn.com. Cualquier uso ilegal y / o no autorizado de YouPorn está prohibida, incluyendo pero no limitado a recoger nombres de usuario y direcciones de correo electrónico para el envío de correos electrónicos no solicitados o selectivo no autorizado o el enlace a la página web YouPorn está prohibido.
Volver arriba
3. ACCESO
Para utilizar este sitio web, usted afirma que tiene al menos dieciocho (18) años de edad y / o sobre la mayoría de edad en la jurisdicción reside y desde el que se accede al sitio web donde la mayoría de edad es mayor de dieciocho (18) años de edad. Si usted es menor de 18 años y / o debajo de la mayoría de edad en la jurisdicción reside y desde el que se accede al sitio web, entonces usted no está autorizado a utilizar el sitio web.
Volver arriba
4. CONDUCTA
Usted reconoce y acepta que será responsable de sus propias comunicaciones de los usuarios y las consecuencias de la publicación, carga, publicación de transmisión u otro haciéndolos disponibles en YouPorn. Usted acepta que no podrá (ni otras personas que utilizan su cuenta) enviados, cargados, publicar, transmitir o hacer disponible en cualquier manera el contenido de YouPorn, que es ilegal, ilegal, acosador, dañino, amenazador, tortuosa, abusivo, difamatorio, obsceno, calumnioso , invasivo de la privacidad de uno que incluye pero no se limita a la información personal, odioso, racial. También acepta que no debe postear, subir, publicar, transmitir o hacer disponible en cualquier manera el software de YouPorn contenga virus o cualquier otro código informático, archivos o programas diseñados para destruir, interrumpir, limitar la funcionalidad de, o monitor, o persistentemente residir en o sobre cualquier software o hardware o equipo de telecomunicaciones. Usted acepta que no podrá (ni otras personas que utilizan su cuenta) enviados, cargados, publicar, transmitir o hacer disponible en cualquier manera el contenido de YouPorn que está intencionalmente o no violando cualquier ley local, estatal, nacional o internacional, o cualquier reglamento o leyes que tienen fuerza de ley en el que reside y en otros lugares, incluyendo pero no limitado a las leyes o reglamentos relativos a valores, privacidad y control de las exportaciones; realizar, promover, Usted acepta que no podrá (ni otras personas que utilizan su cuenta) enviados, cargados, publicar, transmitir o hacer disponible en cualquier manera el contenido de YouPorn representa a actividades ilegales, promover o representar un daño físico o lesiones contra cualquier grupo o individuo o promover o representar cualquier acto de crueldad con los animales; Usted se compromete a no utilizar YouPorn en cualquier forma que expone YouPorn a responsabilidad penal o civil.
Acuerda que YouPorn tendrá el derecho de determinar a su entera discreción y sin trabas, ¿qué acciones se tomarán en caso de cualquier violación descubierto o reportado de los términos y condiciones contenidos en el presente documento.
Volver arriba
5. PROPIEDAD INTELECTUAL


El contenido que figura en el YouPorn con la excepción de los envíos de usuario, incluyendo pero no limitado a, los de texto, software, scripts, gráficos, música, vídeos, fotos, sonidos, características y marcas comerciales interactivos, marcas de servicio y logotipos contenidos en el mismo, son propiedad de y / o con licencia para YouPorn, sujetos a derechos de autor y otros derechos de propiedad intelectual en Estados Unidos, Canadá y las leyes extranjeras y convenciones internacionales. Contenido en el Sitio Web se le proporciona TAL CUAL para su información y uso personal y no puede ser usado, copiado, reproducido, distribuido, transmitido, exhibido, vendido, licenciado, o explotar para ningún otro fin sin el previo consentimiento por escrito de los respectivos propietarios. YouPorn se reserva todos los derechos no expresamente concedidos en y al Sitio Web y el Contenido. Usted se compromete a no participar en el uso, copia o distribución de cualquier Contenido que no sea expresamente permitido en el presente documento, incluyendo cualquier uso, copia y / o distribución de los envíos de usuario de terceros obtenidos a través del Sitio Web para fines comerciales. Si usted descarga o imprime una copia del Contenido para uso personal, debe conservar todos los derechos de autor y otros avisos de propiedad contenidos en la misma. Usted está de acuerdo con desactivar, eludir, o interferir con las funciones de seguridad relacionadas del YouPorn o características que impidan o limiten el uso o copia de cualquier Contenido o hacer cumplir las limitaciones de uso del sitio Web YouPorn o el contenido en el mismo.
Volver arriba
6. COMUNICACIONES DEL USUARIO
YouPorn permite la presentación de vídeo y otras comunicaciones y el alojamiento, el intercambio y publicación de tales envíos de los usuarios. Usted entiende que si o no dichos Archivos de Usuario son publicadas y / o cargados, YouPorn no garantiza ninguna confidencialidad con respecto a cualquier presentación.
YouPorn permite / que permite vincular a los materiales en el sitio web sólo para fines personales y no comerciales. Más encima, YouPorn ofrece una función de "Reproductor", que usted puede incorporar en sus propios sitios web personales y no comerciales para su uso en el acceso a los materiales en el Sitio Web, a condición de que usted incluye un enlace destacado a la página web YouPorn en las páginas que contiene el Reproductor. YouPorn se reserva el derecho a interrumpir cualquier aspecto de la página web YouPorn en cualquier momento. Además, usted no puede modificar, o basarse en bloquear cualquier parte del Reproductor de ninguna manera.
Usted será el único responsable de todas y cada una de sus Archivos de Usuario y las consecuencias de anunciar, publicar, subir y publicar ellos. Por otra parte, con envíos de usuario, usted afirma, representa y / o garantiza que:
es el propietario o conservar las licencias, derechos, consentimientos y permisos para usar y autorizar YouPorn utilizar todas las marcas registradas, derechos de autor, secretos comerciales, patentes, u otros derechos de propiedad en y para cualquier y todos los envíos de usuario para permitir la inclusión y el uso de la Archivos de Usuario en la forma contemplada por el Sitio Web y las presentes Condiciones de Servicio; y
no publicar, o permitir que alguien más para publicar, cualquier material que representa a cualquier persona bajo la edad de 18 años y que ha inspeccionado y está manteniendo documentación escrita suficiente para confirmar que todos los sujetos de sus presentaciones son, de hecho, más de la edad de 18 años.
Usted tiene el consentimiento escrito, la liberación y / o permiso de cada persona individual identificable en el Envío de usuario para utilizar el nombre o la imagen de cada uno y cada persona identificable individuales para permitir la inclusión y el uso de los Archivos de Usuario en la forma prevista por el Sitio Web y las presentes Condiciones de Servicio. Para mayor claridad, usted conserva todos sus derechos de propiedad en sus envíos de usuario. Mediante el envío de los envíos de usuario a YouPorn, usted otorga YouPorn una licencia mundial, no exclusiva, libre de regalías, sublicenciable y transferible para usar, reproducir, distribuir, preparar trabajos derivados de, mostrar y representar los Envíos de usuario en relación con el YouPorn sitio del Web y YouPorn (y de sus sucesores), incluyendo sin limitación para la promoción y redistribución de parte o la totalidad de la Web YouPorn (y trabajos derivados) en cualquier formato ya través de cualquier canal de comunicación. También otorga a cada usuario del Sitio Web YouPorn una licencia no exclusiva para acceder a sus Archivos de Usuario a través del Sitio Web, y para utilizar, reproducir, distribuir, preparar trabajos derivados de, mostrar y ejecutar dichos Archivos de Usuario como se permite a través de la funcionalidad de la Sitio web y en estas Condiciones de servicio. La anterior licencia concedida por usted termina una vez que se quita o elimina un Archivo de Usuario del Sitio Web YouPorn.
Al presentar el material (video u otra comunicación), Asimismo, acepta que no podrá:
enviar material que tiene derechos de autor, protegido por el secreto comercial o de otro tipo sujetos a derechos de propiedad de terceros, incluyendo la privacidad y derechos de publicidad, a menos que usted sea el propietario de dichos derechos o tenga permiso de su legítimo propietario para publicar el material y conceder YouPorn todos los derechos de licencia otorgados en este documento;
publicar falsedades o tergiversaciones que podrían dañar YouPorn o cualquier tercero;
enviar material que sea obsceno, ilegal, ilegal, difamatorio, calumnioso, acosador, odioso, racial o étnicamente ofensivo, o aliente una conducta que pueda ser considerada una ofensa criminal, dar lugar a responsabilidad civil, violar alguna ley, o es inadecuada por otro motivo;
publicar anuncios o solicitudes de negocios;
Hacerse pasar por otra persona. YouPorn no avala ninguna de Usuario ni ninguna opinión, recomendación o consejo expresado en ella, y YouPorn renuncia expresamente a cualquier y toda responsabilidad en relación con los envíos de usuario. YouPorn no permite las actividades infractoras de derechos de autor y violación de los derechos de propiedad intelectual en su sitio web, y YouPorn eliminará todo el contenido y envíos de usuario notificó debidamente que dicha Presentación Contenido o usuario infringe los derechos de propiedad intelectual. YouPorn se reserva el derecho a eliminar contenido y envíos de usuario sin previo aviso ni demora. YouPorn también cancelar el acceso de un usuario a su sitio web, si están decididos a ser un infractor. Si bien se aceptan pornográfica y contenido para adultos, YouPorn también se reserva el derecho a decidir en su discreción única, si el Contenido o Envío de usuario es apropiado y cumple con estas Condiciones de servicio para violaciónes distintos de infracción de derechos de autor y violaciónes de la ley de propiedad intelectual, tal como, pero no limitado a, obsceno o material difamatorio, o longitud excesiva. YouPorn podrá eliminar dichos Archivos de Usuario y / o cancelar el acceso de un usuario para subir tal material en violación de estos Términos de Servicio en cualquier momento, sin previo aviso ya su sola discreción.
Usted entiende y reconoce que al utilizar YouPorn.com, usted estará expuesto a Envíos de usuario a partir de una variedad de fuentes, y que YouPorn no es responsable de la exactitud, utilidad, seguridad o derechos de propiedad intelectual de o en relación con dichos Archivos de Usuario. Usted entiende y reconoce que puede estar expuesto a Envíos de usuario que son inexactos, ofensivo, indecente o censurable, y usted acepta renunciar, y no renuncia a cualquier derecho o remedio legal o equitativo que tenga o pueda tener contra YouPorn con respecto a la misma, y ​​estoy de acuerdo en indemnizar y mantener YouPorn, sus propietarios, afiliados, operadores y / o licenciantes, inofensivos en la máxima medida permitida por la ley con respecto a todos los asuntos relacionados con su uso del sitio web.
Usted acepta que YouPorn podrá, a su sola discreción tiene el derecho de negarse a publicar, eliminar o bloquear el acceso a cualquier Archivo de Usuario que está disponible a través de la Web o de otra red YouPorn o servicios en cualquier momento, por cualquier razón, o por ninguna razón en absoluto, con o sin previo aviso.
YouPorn ofrece su página web como un servicio a sus usuarios. Sin embargo, YouPorn no asume responsabilidad alguna por la supervisión de los Servicios de YouPorn de contenido inapropiado o conducta. Si en algún momento YouPorn decide, a su sola discreción, de monitorear los Servicios de YouPorn, sin embargo, YouPorn no asume ninguna responsabilidad por el contenido, no tiene la obligación de modificar o eliminar cualquier contenido inapropiado, y no se hace responsable por la conducta del Usuario que presenta dicho contenido. YouPorn puede revisar y borrar cualquier Archivo de Usuario que, a su exclusiva discreción, viole este Acuerdo o puede ser de otra manera ofensiva o ilegal, o viola los derechos, dañar, o amenazar la seguridad de cualquier usuario o persona que no está asociada con el Sitio Web (colectivamente " Envíos de usuario inapropiados "). Usted es el único responsable de los envíos de usuario que usted hace visible en la página web o de cualquier sitio web de terceros a través de un reproductor incrustado proporcionado por el Sitio Web o cualquier otro material o información que usted transmita o comparta con otros usuarios o no relacionadas terceros a través de el sitio web.
Volver arriba
7. CUENTA POLÍTICA TERMINACIÓN
el acceso de un usuario a YouPorn se dará por terminado si, en condiciones apropiadas, el Usuario se determina para infringir repetidamente.
YouPorn se reserva el derecho a decidir si el Contenido o si Presentación de un usuario es apropiado y cumple con estos Términos y Condiciones en cuanto a violaciónes distintos de infracción de derechos de autor o de la ley de privacidad, tales como, pero no limitado a, los crímenes de odio, la pornografía, obscenos o difamatorios materiales, o longitud excesiva. YouPorn podrá eliminar dichos Archivos de Usuario y / o cancelar el acceso de un usuario para subir tal material en violación de estos Términos y Condiciones en cualquier momento, sin previo aviso ya su sola discreción.
Volver arriba
8. POLÍTICA
YouPorn se rige por una política de CERO TOLERANCIA relativa a cualquier contenido ilegal. Pornografía infantil, bestialidad, violación, tortura, tabaco, la muerte y / o cualquier otro tipo de material obsceno y / o ilegales no serán tolerados por YouPorn. YouPorn no podrá condonar la pornografía infantil y cooperará con todos los organismos gubernamentales que buscan los que producen pornografía infantil.
Volver arriba
9. HONORARIOS
Usted reconoce que YouPorn se reserva el derecho de cobrar por los servicios de YouPorn y para cambiar sus tarifas de vez en cuando, a su discreción. Adicionalmente, en el caso de YouPorn termina sus derechos de uso del sitio web, debido a un incumplimiento de este Acuerdo, usted no tendrá derecho al reembolso de cualquier porción no utilizada de las tarifas de suscripción.
Volver arriba
10. GARANTÍAS
Usted manifiesta y garantiza que toda la información proporcionada por usted a YouPorn para participar en el sitio web de YouPorn es exacta y actual y tiene todo lo necesario derecho, poder y autoridad para celebrar este Acuerdo y llevar a cabo los actos que se le requieran en virtud del presente.
Como condición para utilizar el YouPorn, debe estar de acuerdo con los términos de la política de privacidad de YouPorn y sus modificaciones. Usted reconoce y acepta que el procesamiento técnico y la transmisión de la Web, incluyendo sus envíos de usuario, pueden implicar transmisiones a través de varias redes; y cambios para ajustarse y adaptarse a los requisitos técnicos de conexión de redes o dispositivos. Además, usted reconoce y acepta que otros datos recopilados y mantenidos por YouPorn en relación con sus usuarios pueden ser revelados de acuerdo con la política de privacidad YouPorn.
Volver arriba
11. RENUNCIA DE GARANTÍA
USTED ACEPTA QUE EL USO DE LA PÁGINA WEB Youporn SERÁ BAJO SU PROPIO RIESGO. EN LA MEDIDA MÁXIMA PERMITIDA POR LA LEY, YouPorn, SUS OFICIALES, DIRECTORES, EMPLEADOS, AGENTES Y renuncia a toda garantía, expresa o implícita, EN RELACIÓN CON EL SITIO WEB Y SU USO DEL MISMO. YouPorn HACE NINGUNA GARANTÍA O REPRESENTACIÓN DE LA EXACTITUD O INTEGRIDAD DEL CONTENIDO DE ESTE SITIO O EL CONTENIDO DE LOS SITIOS VINCULADOS A ESTE SITIO Y NO ASUME NINGUNA RESPONSABILIDAD POR DAÑOS
ERRORES O IMPRECISIONES DEL CONTENIDO,
LESIONES PERSONALES O DAÑOS A LA PROPIEDAD, DE CUALQUIER NATURALEZA, COMO RESULTADO DE SU ACCESO Y USO DE NUESTRO SITIO WEB,
CUALQUIER ACCESO NO AUTORIZADO O USO DE NUESTROS SERVIDORES SEGUROS Y / O CUALQUIER INFORMACIÓN PERSONAL Y / O INFORMACIÓN FINANCIERA almacenados en el mismo,
CUALQUIER INTERRUPCIÓN O CESE DE LA TRANSMISIÓN DESDE NUESTRO SITIO WEB, (IV) CUALQUIER ERRORES, VIRUS, CABALLOS DE TROYA O SIMILARES QUE PUEDAN SER TRANSMITIDO AL OA TRAVÉS DE NUESTRO SITIO WEB POR CUALQUIER TERCERO, Y / O
CUALQUIER ERROR U OMISIÓN EN CUALQUIER CONTENIDO O POR CUALQUIER PÉRDIDA O DAÑO DE CUALQUIER TIPO INCURRIDO COMO RESULTADO DEL USO DE CUALQUIER CONTENIDO PUBLICADO, ENVIADO POR CORREO ELECTRÓNICO, TRANSMITIDO, o puesto a disposición WEB MEDIANTE EL YouPorn. YouPorn NO GARANTIZA, endosar, GARANTÍA O ASUME RESPONSABILIDAD POR CUALQUIER PRODUCTO O SERVICIO OFRECIDO POR TERCEROS A TRAVÉS DEL SITIO WEB Youporn O CUALQUIER SITIO VINCULADO O PRESENTADO EN UN CARTEL U OTRA PUBLICIDAD, Y Youporn NO SERÁ PARTE NI DE NINGUNA MANERA RESPONSABLE DE CONTROL DE LAS TRANSACCIONES ENTRE USTED Y PROVEEDORES DE TERCEROS DE PRODUCTOS O SERVICIOS. COMO CON LA COMPRA DE UN PRODUCTO O SERVICIO A TRAVÉS DE CUALQUIER MEDIO O EN CUALQUIER AMBIENTE, ES NECESARIO USAR SU MEJOR JUICIO Y TOMAR LAS PRECAUCIONES NECESARIAS. LA LIMITACIÓN DE RESPONSABILIDAD SE APLICARÁ EN LA MEDIDA MÁXIMA PERMITIDA POR LA LEY EN LA JURISDICCIÓN APLICABLE. USTED RECONOCE QUE Youporn NO SE HACE RESPONSABLE DE LAS COMUNICACIONES DEL USUARIO O LA difamatorio, ofensivo, O ILEGAL DE TERCEROS Y QUE EL RIESGO DE DAÑO O PERJUICIO DE LO ANTERIOR ES EXCLUSIVO CON USTED.
Volver arriba
12. LIMITACIÓN DE LA RESPONSABILIDAD
EN NINGÚN CASO YouPorn, SUS OFICIALES, DIRECTORES, EMPLEADOS, O AGENTES, SERÁ RESPONSABLE ANTE USTED POR DAÑOS DIRECTOS,, INCIDENTAL, PUNITIVO O INDIRECTO, ESPECIAL QUE RESULTE DE CUALQUIER
ERRORES O IMPRECISIONES DEL CONTENIDO,
LESIONES PERSONALES O DAÑOS A LA PROPIEDAD, DE CUALQUIER NATURALEZA, COMO RESULTADO DE SU ACCESO Y USO DE NUESTRO SITIO WEB,
CUALQUIER ACCESO NO AUTORIZADO O USO DE NUESTROS SERVIDORES SEGUROS Y / O CUALQUIER INFORMACIÓN PERSONAL Y / O INFORMACIÓN FINANCIERA almacenados en el mismo,
CUALQUIER INTERRUPCIÓN O CESE DE LA TRANSMISIÓN DESDE NUESTRO SITIO WEB,
Cualquier error, virus, troyanos, o similares, QUE PUEDA SER TRANSMITIDO AL OA TRAVÉS DE NUESTRO SITIO WEB POR CUALQUIER TERCERO, Y / O
ERRORES U OMISIONES EN CUALQUIER CONTENIDO O POR CUALQUIER PÉRDIDA O DAÑO DE CUALQUIER TIPO INCURRIDO COMO RESULTADO DE SU USO DE CUALQUIER CONTENIDO PUBLICADO, ENVIADO POR CORREO ELECTRÓNICO, transmitido o puesto a disposición WEB MEDIANTE EL YouPorn, YA SEA EN GARANTÍA, CONTRATO, AGRAVIO, O CUALQUIER OTRA TEORÍA LEGAL, Y SI ornot la compañía está advertido de la posibilidad de tales daños. LA LIMITACIÓN DE RESPONSABILIDAD SE APLICARÁ EN LA MEDIDA MÁXIMA PERMITIDA POR LA LEY EN LA JURISDICCIÓN APLICABLE. USTED RECONOCE QUE Youporn NO SE HACE RESPONSABLE DE LAS COMUNICACIONES DEL USUARIO O LA difamatorio, ofensivo, O ILEGAL DE TERCEROS Y QUE EL RIESGO DE DAÑO O PERJUICIO DE LO ANTERIOR ES EXCLUSIVO CON USTED.
Volver arriba
13. INDEMNIZACIÓN
Usted acepta defender, indemnizar y mantener indemne a YouPorn, su empresa matriz, oficiales, directores, empleados y agentes, de y contra cualquier y todo reclamo, daños, obligaciones, pérdidas, responsabilidades, costos o deudas y gastos (incluyendo, pero no limitado de los honorarios de abogados) que surjan de:
el uso y el acceso a la Web YouPorn;
su violación de cualquier término de estas Condiciones del servicio;
su violación de cualquier derecho de terceros, incluyendo sin limitación cualquier derecho de autor, la propiedad o derecho de privacidad; o
Cualquier afirman que uno de sus envíos de usuario causó daños a un tercero. Esta defensa y obligación de indemnización sobrevivirá a estos Términos de Servicio y su uso del Sitio Web YouPorn.
Usted afirma que usted es mayor de 18 años de edad o menor emancipado, o posee el consentimiento legal de sus padres o tutores, y es plenamente capaz y competente para entrar en los términos, las condiciones, obligaciones, afirmaciones, declaraciones y garantías establecidas en estas Condiciones de servicio, y para acatar y cumplir con los presentes Términos y Condiciones aquí contenidos.
Volver arriba
14. CESIÓN
Los Términos y Condiciones aquí contenidos y cualesquiera derechos y licencias otorgados en este documento, no podrán ser transferidos o cedidos por usted, pero pueden ser asignados por YouPorn sin restricciones.
Si cualquier término, cláusula o disposición del Acuerdo es considerada inválida o inaplicable por un tribunal de jurisdicción competente, dicha nulidad no afectará la validez o la operación de cualquier término, cláusula o disposición y como no válido plazo, cláusula o disposición se considerará ser separada de este Acuerdo.
Volver arriba
15. JURISDICCIÓN
Este Acuerdo se regirá e interpretará de acuerdo con las leyes de Chipre, sin tener en cuenta conflictos de principios legales. La jurisdicción y competencia única y exclusiva para cualquier acción o procedimiento que surja de o relacionados con este Acuerdo serán en un tribunal correspondiente ubicado en Limassol, Chipre. Usted se someten a la jurisdicción y competencia de dichos tribunales. Usted da su consentimiento a ser emplazado en cualquier procedimiento legal.